spring.application.name=gatewayonboarding
server.port=8081
server.servlet.context-path=/gatewayonboarding
# spring.main.allow-bean-definition-overriding=true (common-lib disabled)

# Error code config — format: FS-MG-ON-{TYPE}-{SEQ}
error.project-code=FS
error.domain-code=MG
error.service-code=ON

# MongoDB Configuration
# spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/projectdb-project}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://admin_db_user:HdhPLHmhHEhxSUTa@probestack-prod.mby902c.mongodb.net/probestack-forgesphere?appName=probestack-prod}
spring.data.mongodb.database=${MONGODB_CONFIG_DB:probestack-forgesphere}
spring.data.mongodb.auto-index-creation=${MONGODB_AUTO_INDEX:false}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

###################################################
## CORS CONFIGURATION
###################################################
cors.origins=${CORS_ORIGINS:*}
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD
cors.allowed-headers=Accept,Accept-Language,Content-Language,Content-Type,Authorization,X-Requested-With,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,X-Partner-Id,X-User-Id
cors.exposed-headers="*"
cors.allow-credentials=false
cors.max-age=3600

###################################################
## MAIL / APPROVAL SETTINGS
###################################################
# SendGrid (replace SMTP)
# sendgrid.mail-api-key=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
sendgrid.template-id=d-04743d5c95b3469595629d987c54cea4

# Still keep these for sender/recipient requirements
mail.from=abhisek.satapathy@probestack.io

mail.to.default=info@probestack.io
mail.to.info=info@probestack.io

# Base URL for clickable approval links sent by email
approval.base-url=${APPROVAL_BASE_URL:https://forgesphere.probestack.io/}


